# Define substitutions at the beginning
substitutions:
  _SERVICE_NAME: sveltekit-deploy  # Replace with your actual service name
  _REGION: asia-south1           # Replace with your desired region 

# Define variables used throughout the build
steps:
- name: 'Build image'
  # Use Kaniko builder for building container images within Cloud Build
  id: 'build-image'
  # Replace 'gcr.io/cloud-builders/docker' with your preferred builder if needed
  name: 'gcr.io/cloud-builders/kaniko'
  args:
  - '--dockerfile=Dockerfile'
  - '--destination=gcr.io/$PROJECT_ID/$${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}'
  - '.'

- name: 'Push image'
  id: 'push-image'
  name: 'gcr.io/cloud-builders/kaniko'
  args:
  - '--destination=gcr.io/$PROJECT_ID/$${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}'

- name: 'Deploy preview with tag'
  id: 'deploy-preview'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '$${_SERVICE_NAME}'  # Use variable for service name
  - '--platform'
  - 'managed'
  - '--region'
  - '$${_REGION}'  # Use variable for region
  - '--image'
  - "gcr.io/$PROJECT_ID/$${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}"
  - '--tag'
  - "pr-${_PR_NUMBER}"  # Use a tag with the PR number for easy identification
  - '--no-traffic'  # Deploy the preview with no traffic by default

# This step requires a custom builder to link the preview with the pull request
# You can find an example implementation here:
# https://zentered.co/articles/preview-builds-with-cloud-run

- name: 'Link preview on pull request'  # Replace with your custom builder
  id: 'link-preview'
  # ... (Replace with your custom builder configuration)

# Secrets required by the custom builder (if any)
secretEnv:
- 'GITHUB_TOKEN'  # Replace with any secrets required by your custom builder

# This section triggers the build on PR creation/updates
triggers:
- kind: cloud-source-repository
  projectId: $PROJECT_ID
  repository: $_REPO_NAME  # Replace with the name of your Git repository
  branch: ^pull/.*
