name: Deploy SvelteKit application

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo

      - name: code checkout
        uses: actions/checkout@v2

      # Actions need gcloud cli to work so we install it,
      # Using plugins to avoid writing install bash scripts

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      # Pushing the docker image

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker build -t asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/sveltekit-deployment/node:21-alpine3.18 .
          docker push asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/sveltekit-deployment/node:21-alpine3.18
